trigger:
  branches:
    include:
      - main

variables:
  - name: workingDirectory
    value: 'terraform'
  - name: environment
    value: 'dev'
  - name: location
    value: 'East US'

stages:
  - stage: Terraform_Deploy
    displayName: "Terraform Infrastructure Deployment"
    jobs:
      - job: Terraform
        displayName: "Deploy Azure Infrastructure with Terraform"
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          # Checkout code
          - checkout: self

          # ✅ Install Terraform manually
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          # ✅ Login to Azure using Service Connection
          - task: AzureCLI@2
            displayName: 'Terraform Init (with Azure CLI Auth)'
            inputs:
              azureSubscription: 'azure-spn'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              workingDirectory: '$(System.DefaultWorkingDirectory)/$(workingDirectory)'
              inlineScript: |
                set -e
                echo "Logged in as:"
                az account show
                export ARM_USE_AZUREAD=true
                export ARM_TENANT_ID=84e2b0e7-902b-41b8-9b12-c7ad70e19ae4
                export ARM_SUBSCRIPTION_ID=ff700b30-4552-4c70-9584-5b2ff2f1b153
                export ARM_CLIENT_ID=7685b128-56db-49eb-83eb-5c55fadce55b

                echo "Authenticating Terraform with Azure AD..."
                az account get-access-token --resource https://storage.azure.com/ --query accessToken -o tsv > /dev/null
                terraform init \
                  -backend-config="resource_group_name=devops-lab-tfstate-rg" \
                  -backend-config="storage_account_name=tfstatebackendstorageaks" \
                  -backend-config="container_name=tfstate" \
                  -backend-config="key=infra.tfstate"\
                  -backend-config="use_azuread_auth=true"

          # ✅ Terraform Validate
          - task: TerraformTaskV4@4
            displayName: "Terraform Validate"
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/$(workingDirectory)'


          # ✅ Terraform Plan
          - task: TerraformTaskV4@4
            displayName: "Terraform plan"
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/$(workingDirectory)'
              environmentServiceNameAzureRM: 'azure-spn'

          # ✅ Terraform Apply
          - task: TerraformTaskV4@4
            displayName: "Terraform apply"
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/$(workingDirectory)'
              environmentServiceNameAzureRM: 'azure-spn'

          # ✅ Show Outputs
          - task: TerraformTaskV4@4
            displayName: "Terraform output"
            inputs:
              provider: 'azurerm'
              command: 'output'
              workingDirectory: '$(System.DefaultWorkingDirectory)/$(workingDirectory)'
              environmentServiceNameAzureRM: 'azure-spn'